School_clubs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clubs_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('duty_app/', include('duty_app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
]

clubs_app/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'clubs_app'

urlpatterns = [
    path('', index, name='home_page'),
    path('create_club/', create_club, name='create_club'),
    path('list_club/<slug:cat_slug>', list_club, name='list_club'),
    path('join_club/<int:club_id>', join_club, name='join_club'),
    path('my_clubs/', my_clubs, name='my_clubs'),
    path('show_content/<slug:slug_club>/articles/', show_articles, name='show_articles'),
    path('show_content/acticles/<slug:slug_article>/', detail_articles, name='detail_articles'),
    path('show_content/<slug:slug_club>/messages/', show_messages, name='show_messages'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard_app/urls.py
from django.urls import path, include
from .views import index, members, delete_member, add_article, message, delete_content
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard_app'
urlpatterns = [
    path('<slug:slug_club>/profile/', index, name='profile'),
    path('<slug:slug_club>/members/', members, name='members'),
    path('<slug:slug_club>/<int:id_member>/delete/', delete_member, name='delete_member'),
    path('<slug:slug_club>/content/add_article', add_article, name='add_article'),
    path('<slug:slug_club>/add_message/', message, name='message'),
    path('content/delete/<str:model_name>/<slug:content_slug>/', delete_content, name='delete_content'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard_app/models.py
from django.db import models

# Create your models here.

dashboard_app/forms.py
from django import forms
from clubs_app.models import *
from ckeditor.widgets import CKEditorWidget


class ChangeClubData(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields['title_club'].label = 'Изменить название клуба'
        self.fields['cat_club'].label = 'Изменить категорию'
        self.fields['info_club'].label = 'Изменить информацию'
        self.fields['days_event'].label = 'Изменить дни'
        self.fields['time_event'].label = 'Изменить время'
        self.fields['price_club'].label = 'Изменить цену'

    class Meta:
        model = ClubModel
        fields = ['title_club', 'cat_club', 'info_club', 'days_event', 'time_event', 'price_club', ]

        widgets = {
            'title_club': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'cat_club': forms.Select(attrs={'class': 'form-control form-control-lg'}),
            'info_club': forms.Textarea(attrs={'class': 'form-control form-control-lg', 'rows': 4}),
            'days_event': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'time_event': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'price_club': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
        }


class ArticleClubForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = ArticleClubModel
        fields = ('title_article', 'text_body', 'image')

        widgets = {
            'title_article': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'image': forms.FileInput(attrs={'class': 'form-control form-control-lg'})
        }


class MessageAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title_msg'].label = 'Заголовок сообщения'

    class Meta:
        model = MessageClub
        fields = ('title_msg', 'body_msg')

        widgets = {
            'title_msg': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'body_msg': forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
        }

dashboard_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import ChangeClubData, ArticleClubForm, MessageAddForm
from django.contrib import messages
from clubs_app.models import *
from pytils.translit import slugify
from datetime import date


def check_user_club(request, slug_club):
    if not (request.user == ClubModel.objects.get(slug_club=slug_club).manager):
        return redirect('clubs_app:home_page')
    else:
        return False


@login_required
def members(request, slug_club):
    if check_user_club(request, slug_club):
        messages.success(request, 'Доступ закрыт')
        return check_user_club(request, slug_club)

    club = ClubModel.objects.get(slug_club=slug_club)
    context = {
        'members': club.member.all(),
        'slug_club': slug_club,
        'club_name': club.title_club,
    }
    return render(request, template_name='dashboard_app/members.html', context=context)


@login_required
def index(request, slug_club):
    if check_user_club(request, slug_club):
        messages.success(request, 'Доступ закрыт')
        return check_user_club(request, slug_club)

    club = ClubModel.objects.get(slug_club=slug_club)

    initial_data = {
        'title_club': club.title_club,
        'cat_club': club.cat_club,
        'info_club': club.info_club,
        'days_event': club.days_event,
        'time_event': club.time_event,
        'price_club': club.price_club,
    }

    if request.method == 'POST':
        form_change_club_data = ChangeClubData(request.POST, initial=initial_data)

        if form_change_club_data.is_valid():
            club.title_club = form_change_club_data.instance.title_club
            club.cat_club = form_change_club_data.instance.cat_club
            club.info_club = form_change_club_data.instance.info_club
            club.days_event = form_change_club_data.instance.days_event
            club.time_event = form_change_club_data.instance.time_event
            club.price_club = form_change_club_data.instance.price_club

            club.save()
            return redirect('dashboard_app:profile', slug_club=slug_club)
    else:
        form_change_club_data = ChangeClubData(initial=initial_data)

    context = {
        'form': form_change_club_data,
        'slug_club': slug_club,
        'club_name': club.title_club,

    }

    return render(request, template_name='dashboard_app/index.html', context=context)


@login_required
def delete_member(request, slug_club, id_member):
    if check_user_club(request, slug_club):
        messages.success(request, 'Доступ закрыт')
        return check_user_club(request, slug_club)
    club = ClubModel.objects.get(slug_club=slug_club)
    member_club = club.member.get(id=id_member)

    club.member.remove(member_club)

    return redirect('dashboard_app:members', slug_club=slug_club)


def content(request):
    pass


@login_required
def add_article(request, slug_club):
    if check_user_club(request, slug_club):
        messages.success(request, 'Доступ закрыт')
        return check_user_club(request, slug_club)

    if request.method == 'POST':
        form_title = ArticleClubForm(request.POST, request.FILES)
        if form_title.is_valid():
            model_article = ArticleClubModel.objects.create(
                title_article=form_title.instance.title_article,
                slug_content=slugify(form_title.instance.title_article),
                author_user=request.user,
                club_contains=ClubModel.objects.get(slug_club=slug_club),
                text_body=form_title.instance.text_body,
                image=form_title.instance.image,
            )
            model_article.save()
            messages.success(request, 'Статья добавлена')
            return redirect('dashboard_app:add_article', slug_club=slug_club)

        else:
            form_title = ArticleClubForm()
            messages.success(request, 'Ошибка')
            redirect('dashboard_app:add_article', slug_club=slug_club)
    else:
        form_title = ArticleClubForm()

    context = {
        'slug_club': slug_club,
        'form_ck': form_title,
        'club_name': ClubModel.objects.get(slug_club=slug_club).title_club,
    }
    return render(request, template_name='dashboard_app/add_article.html', context=context)


@login_required
def message(request, slug_club):
    if check_user_club(request, slug_club):
        messages.success(request, 'Доступ закрыт')
        return check_user_club(request, slug_club)
    if request.method == 'POST':
        form_msg = MessageAddForm(request.POST)

        if form_msg.is_valid():
            model_msg = MessageClub.objects.create(
                author_user=request.user,
                club_contains=ClubModel.objects.get(slug_club=slug_club),
                slug_content=slugify(f'{form_msg.instance.title_msg}{date.today()}'),
                title_msg=form_msg.instance.title_msg,
                body_msg=form_msg.instance.body_msg,
            )
            model_msg.save()
            messages.success(request, 'Сообщение отправлено')
            return redirect('dashboard_app:message', slug_club=slug_club)
        else:
            messages.success(request, 'Ошибка')
            return redirect('dashboard_app:message', slug_club=slug_club)
    else:
        form_msg = MessageAddForm()

    context = {
        'slug_club': slug_club,
        'form_msg': form_msg,
        'club_name': ClubModel.objects.get(slug_club=slug_club).title_club,
    }
    return render(request, template_name='dashboard_app/add_msg.html', context=context)


MODEL_DICT = {'articleclubmodel': ArticleClubModel, 'messageclub': MessageClub}


@login_required
def delete_content(request, model_name, content_slug):
    if MODEL_DICT[model_name].objects.get(slug_content=content_slug).author_user == request.user:
        model = MODEL_DICT[model_name].objects.get(slug_content=content_slug).delete()
        messages.success(request, 'Удалено')
        try:
            return redirect(request.META.get('HTTP_REFERER'))  # редирект на предыдущую страницу
        except:
            return redirect('clubs_app:home_page')
    else:
        messages.success(request, 'Ошибка')
        return redirect('clubs_app:home_page')

dashboard_app/templates/dashboard_app/add_article.html
{% extends 'dashboard_app/base.html' %}
{% block title_body %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="container">
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% endif %}
    <h1 class="text-center">Добавить статью</h1><br>
{% endblock title_body %}

{% block content %}
    <a class="btn btn-outline-primary" href="{% url 'clubs_app:show_articles' slug_club=slug_club  %}">Смотреть мои статьи</a><br><br>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form_ck.media }}
        {{ form_ck.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock content %}

dashboard_app/templates/dashboard_app/add_msg.html
{% extends 'dashboard_app/base.html' %}
{% block title_body %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="container">
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% endif %}
    <h1 class="text-center">Добавить сообщение</h1><br>
{% endblock title_body %}

{% block content %}
    <a class="btn btn-outline-primary" href="{% url 'clubs_app:show_messages' slug_club=slug_club %}">Смотреть мои
        сообщения</a><br><br>

    <form method="post">{% csrf_token %}
        {% for f in form_msg %}
            <div class="mb-3">
                <label class="form-label" style="font-size: 20px">{{ f.label }}</label>
                {{ f }}
                {{ f.errors }}
                <div class="form-text">{{ f.errors }}</div>
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock content %}

dashboard_app/templates/dashboard_app/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'dashboard_app/css/dashboard.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor.css' %}">
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row flex-nowrap" style="min-width: 500px">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0" style="background: #223A76 !important;">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline elements-menu" style="display: block">{{ club_name }}</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="{% url 'dashboard_app:profile' slug_club %}"
                           class="nav-link align-middle px-0 elements-menu">
                            <i class="bi bi-person-fill-gear"></i><span class="ms-1 d-none d-sm-inline">Профиль</span>
                        </a>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a href="{% url 'dashboard_app:members' slug_club %}"
                           class="nav-link align-middle px-0 elements-menu">
                            <i class="bi bi-person-lines-fill"></i><span
                                class="ms-1 d-none d-sm-inline">Участники</span>
                        </a>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a href="{% url 'dashboard_app:add_article' slug_club %}"
                           class="nav-link align-middle px-0 elements-menu">
                            <i class="bi bi-layout-text-window-reverse"></i><span class="ms-1 d-none d-sm-inline">Контент</span>
                        </a>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a href="{% url 'dashboard_app:message' slug_club %}" class="nav-link align-middle px-0 elements-menu">
                            <i class="bi bi-chat-left-dots"></i><span class="ms-1 d-none d-sm-inline">Сообщения</span>
                        </a>
                    </li>
                    <br>

                    {#                    <li>#}
                    {#                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">#}
                    {#                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>#}
                    {#                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">#}
                    {#                            <li class="w-100">#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>#}
                    {#                            </li>#}
                    {#                            <li>#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>#}
                    {#                            </li>#}
                    {#                        </ul>#}
                    {#                    </li>#}
                    {#                    <li>#}
                    {#                        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">#}
                    {#                            <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>#}
                    {#                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">#}
                    {#                            <li class="w-100">#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>#}
                    {#                            </li>#}
                    {#                            <li>#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>#}
                    {#                            </li>#}
                    {#                        </ul>#}
                    {#                    </li>#}
                    {#                    <li>#}
                    {#                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">#}
                    {#                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>#}
                    {#                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">#}
                    {#                            <li class="w-100">#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>#}
                    {#                            </li>#}
                    {#                            <li>#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>#}
                    {#                            </li>#}
                    {#                            <li>#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>#}
                    {#                            </li>#}
                    {#                            <li>#}
                    {#                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>#}
                    {#                            </li>#}
                    {#                        </ul>#}
                    {#                    </li>#}
                    {#                    <li>#}
                    {#                        <a href="#" class="nav-link px-0 align-middle">#}
                    {#                            <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>#}
                    {#                    </li>#}
                </ul>
                <hr>
                <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                       id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="d-none d-sm-inline mx-1">{{ request.user }}</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
{#                        <li><a class="dropdown-item" href="#">New project...</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Settings</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Profile</a></li>#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
                        <li><a class="dropdown-item" href="/accounts/logout">Выйти</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col py-3">
            {% block title_body %}

            {% endblock %}

            <div class="container">
                {% block content %}

                {% endblock %}
            </div>

        </div>
    </div>
</div>
</body>
</html>

dashboard_app/templates/dashboard_app/index.html
{% extends 'dashboard_app/base.html' %}
{% block title_body %}
    <h1 class="text-center">Профиль клуба</h1><br>
{% endblock title_body %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock content %}

dashboard_app/templates/dashboard_app/members.html
{% extends 'dashboard_app/base.html' %}

{% block content %}
    <h1 class="text-center">Участники клуба</h1><br>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Имя участника</th>
                <th scope="col">Почта</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for member in members %}
                <tr>
                    <td style="" class="">{{ member.pk }}</td>
                    <td>{{ member.username }}</td>
                    <td>{{ member.email }}</td>
                    <td><a class="btn btn-danger btn-sm" href="{% url 'dashboard_app:delete_member' slug_club=slug_club id_member=member.pk %}">Удалить</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


{% endblock content %}