School_clubs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clubs_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('duty_app/', include('duty_app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
]

clubs_app/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'clubs_app'

urlpatterns = [
    path('', index, name='home_page'),
    path('create_club/', create_club, name='create_club'),
    path('list_club/<slug:cat_slug>', list_club, name='list_club'),
    path('join_club/<int:club_id>', join_club, name='join_club'),
    path('my_clubs/', my_clubs, name='my_clubs'),
    path('show_content/<slug:slug_club>/articles/', show_articles, name='show_articles'),
    path('show_content/acticles/<slug:slug_article>/', detail_articles, name='detail_articles'),
    path('show_content/<slug:slug_club>/messages/', show_messages, name='show_messages'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard_app/urls.py
from django.urls import path, include
from .views import index, members, delete_member, add_article, message, delete_content
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard_app'
urlpatterns = [
    path('<slug:slug_club>/profile/', index, name='profile'),
    path('<slug:slug_club>/members/', members, name='members'),
    path('<slug:slug_club>/<int:id_member>/delete/', delete_member, name='delete_member'),
    path('<slug:slug_club>/content/add_article', add_article, name='add_article'),
    path('<slug:slug_club>/add_message/', message, name='message'),
    path('content/delete/<str:model_name>/<slug:content_slug>/', delete_content, name='delete_content'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clubs_app/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from ckeditor.fields import RichTextField
import django


class MessageClub(models.Model):
    author_user = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, verbose_name='Отправитель')
    club_contains = models.ForeignKey('ClubModel', on_delete=models.CASCADE, verbose_name='Клуб', null=True)
    slug_content = models.SlugField(unique=True, max_length=512)

    title_msg = models.CharField(null=True, blank=False, max_length=128, verbose_name='Заголовок сообщения')
    body_msg = models.TextField(null=True, blank=False, verbose_name='Сообщение')
    date_load = models.DateField(default=django.utils.timezone.now, verbose_name='Дата')

    class Meta:
        verbose_name = 'Сообщения клубов'
        verbose_name_plural = 'Сообщения клубов'

    def get_delete_url(self):
        return reverse('dashboard_app:delete_content',
                       kwargs={'model_name': 'messageclub', 'content_slug': self.slug_content})


class ArticleClubModel(models.Model):
    author_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    club_contains = models.ForeignKey('ClubModel', on_delete=models.CASCADE, null=True)
    slug_content = models.SlugField(max_length=255, unique=True)

    title_article = models.CharField(max_length=128, verbose_name='Заголовок статьи', unique=True, blank=False)
    text_body = RichTextField(blank=False, null=True, verbose_name='Контент статьи')
    image = models.ImageField(upload_to='articles/', null=True, blank=False, verbose_name='Главное изображение статьи')

    def __str__(self):
        return self.title_article

    class Meta:
        verbose_name = 'Статьи клубов'
        verbose_name_plural = 'Статьи клубов'

    def get_absolute_url(self):
        return reverse('clubs_app:detail_articles', kwargs={'slug_article': self.slug_content})

    def get_delete_url(self):
        return reverse('dashboard_app:delete_content',
                       kwargs={'model_name': 'articleclubmodel', 'content_slug': self.slug_content})


class ClubModel(models.Model):
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, null=True, related_name='user_system')
    title_club = models.CharField(max_length=128, null=False, blank=False)
    cat_club = models.ForeignKey('CatClubModel', on_delete=models.CASCADE)
    info_club = models.TextField()
    days_event = models.CharField(max_length=100, null=True, blank=True)
    time_event = models.CharField(max_length=100, null=True, blank=True)
    price_club = models.CharField(max_length=256, null=True, blank=True)
    member = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='member_field')
    slug_club = models.SlugField(max_length=255, unique=True, null=True)

    def __str__(self):
        return self.title_club

    class Meta:
        verbose_name = 'Клубы'
        verbose_name_plural = 'Клубы'
        ordering = ['-id']


class CatClubModel(models.Model):
    cat = models.CharField(max_length=128, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='photos/', null=True)

    def __str__(self):
        return self.cat

    def get_absolute_url(self):
        return reverse('clubs_app:list_club', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категории клубов'
        verbose_name_plural = 'Категории клубов'

clubs_app/forms.py
from django import forms
from .models import ClubModel


class FormClubModel(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title_club'].label = 'Название клуба'
        self.fields['cat_club'].empty_label = 'Категория клуба не выбрана:'
        self.fields['cat_club'].label = 'Категория клуба'
        self.fields['info_club'].label = 'Информация о клубе'
        self.fields['days_event'].label = 'Дни проведения'
        self.fields['time_event'].label = 'Время проведения'
        self.fields['price_club'].label = 'Цена'

    class Meta:
        model = ClubModel
        fields = ["title_club", "cat_club", "info_club", "days_event", "time_event",
                  "price_club"]


        widgets = {
            'title_club': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'cat_club': forms.Select(attrs={'class': 'form-control form-control-lg'}),
            'info_club': forms.Textarea(attrs={'class': 'form-control form-control-lg', 'rows': 4}),
            'days_event': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'time_event': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'price_club': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
        }

clubs_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from pytils.translit import slugify
from django.db.models import Q
from django.apps import apps


def index(request):
    clubs_cat = CatClubModel.objects.all()
    context = {
        'clubs_cat': clubs_cat,
    }
    return render(request, template_name='clubs_app/index.html', context=context)


@login_required
def create_club(request):
    if request.method == 'POST':
        form = FormClubModel(request.POST)
        if form.is_valid():
            form.instance.manager = request.user
            form.instance.slug_club = slugify(form.instance.title_club)
            form.save()
            messages.success(request, 'Клуб создан')
            return redirect('clubs_app:home_page')
    else:
        form = FormClubModel()

    context = {
        'form': form,
    }
    return render(request, template_name='clubs_app/create_club.html', context=context)


@login_required
def list_club(request, cat_slug):
    if cat_slug == 'all_clubs':
        club_model = ClubModel.objects.all()
        cat = None
    else:
        cm = CatClubModel.objects.get(slug=cat_slug)
        club_model = ClubModel.objects.filter(cat_club=cm)
        cat = cm.cat

    context = {
        'club_model': club_model,
        'if_all_clubs': ('all_clubs' if cat_slug == 'all_clubs' else False),
        'if_category': ('category' if cat_slug not in ('my_clubs', 'all_clubs') else False),
        'cat': cat,
    }
    return render(request, template_name='clubs_app/list_club.html', context=context)


def join_club(request, club_id):
    club = ClubModel.objects.get(pk=club_id)
    club.member.add(request.user.id)

    messages.success(request, f'Вы вступили в клуб {club.title_club}')
    return redirect('clubs_app:home_page')


@login_required
def my_clubs(request):
    club_model = set(ClubModel.objects.filter(Q(manager=request.user) | Q(member=request.user)))
    context = {
        'club_model': club_model,
        'my_clubs': True,
    }

    return render(request, template_name='clubs_app/list_club.html', context=context)


def show_articles(request, slug_club):
    articles = ArticleClubModel.objects.filter(club_contains=ClubModel.objects.get(slug_club=slug_club))

    context = {
        'slug_club': slug_club,
        'articles': articles,
    }
    return render(request, template_name='clubs_app/show_articles.html', context=context)


def detail_articles(request, slug_article):
    article = ArticleClubModel.objects.get(slug_content=slug_article)

    context = {
        'title_article': article.title_article,
        'text_body': article.text_body,
        'author_user': article.author_user.username,
        'image': article.image,
        'slug_club': article.club_contains.slug_club,
    }
    return render(request, template_name='clubs_app/detail_articles.html', context=context)


def show_messages(request, slug_club):
    context = {
        'slug_club': slug_club,
        'messages': MessageClub.objects.filter(club_contains=ClubModel.objects.get(slug_club=slug_club))
    }

    return render(request, template_name='clubs_app/show_messages.html', context=context)

clubs_app/templates/clubs_app/base/base.html
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="auto">
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'clubs_app/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'clubs_app/css/style2.css' %}">

    {% block css %}{% endblock %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="d-flex flex-column h-100">
{% include 'clubs_app/base/navbar.html' %}


{% block content %}
{% endblock content %}

{% include 'clubs_app/base/footer.html' %}


</body>
</html>

clubs_app/templates/clubs_app/base/footer.html
{% load static %}

<br><br><br><br><br>
<footer style="background-color: #223A76; padding: 30px;" class="footer mt-auto py-3">
    <div class="container h-100">
        <div class="row">
            <div class="col-9">
                <p class="justify-content-between" style="color:white; font-size: 25px;">
                    Этот сайт - продукт группового проекта учеников 10Б класса, школы №200 - Александрова Дмитрия,
                    Довгомеля Анастасии, Каргаполовой Елизаветы.
                    (2023)
                </p>
            </div>

            <div class="col-3" style="display:block; margin:auto;">
                <img src="{% static 'clubs_app/images/logos/logowhite.png' %}" alt="Logo" class="adaptive-footer-logo">
            </div>
        </div>

    </div>

</footer>

{#<footer class="footer mt-auto py-3 bg-body-tertiary">#}
{#  <div class="container">#}
{#    <span class="text-body-secondary">Place sticky footer content here.</span>#}
{#  </div>#}
{#</footer>#}

clubs_app/templates/clubs_app/base/nav.html
<div class="container">
        <nav class="nav">
            <a class="nav-link active" aria-current="page"
               href="{% url 'clubs_app:show_articles' slug_club=slug_club %}"
               style="font-weight:400">Статьи</a>
            <a class="nav-link" href="#" style="font-weight:400">Новости</a>
            <a class="nav-link" href="{% url 'clubs_app:show_messages' slug_club=slug_club %}" style="font-weight:400">Сообщения</a>
            <a class="nav-link" href="{% url 'dashboard_app:add_article' slug_club=slug_club %}" style="font-weight:400">Панель управления</a>
        </nav>
</div><br><br>

clubs_app/templates/clubs_app/base/navbar.html
{% load static %}
{% load custom_filters %}


<nav class="navbar navbar-expand-md height-navbar">
    <div class="container-xl container-lg-fluid container-900 container-sm">
        <a class="navbar-brand" href="{% url 'clubs_app:home_page' %}">
            <img src="{% static 'clubs_app/images/logos/logo.svg' %}" alt="Logo"
                 class="d-inline-block align-text-top logo-adaptive">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link mx-xl-3 mx-lg-1" href="{% url 'clubs_app:home_page' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mx-xl-3 mx-lg-1" href="#">Категории</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Клубы
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'clubs_app:my_clubs' %}">Мои клубы</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'clubs_app:create_club' %}">Создать клуб</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">

                {% if user.is_authenticated %}
                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">
                        <a href="{% url 'login' %}" class="nav-link btn btn-signin rounded-pill ps-4 pe-4 pt-2 pb-2"
                           type="submit">{{ user.username |split_string|first|truncatechars:20 }}</a>
                    </li>
                    <li class="nav-item mx-xl-3 mx-md-1 btn-sm">
                        <a href="{% url 'login' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"
                           type="submit">{{ user.username |split_string|first|truncatechars:10 }}</a>
                    </li>
                {% else %}
                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">
                        <a href="{% url 'signup' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"
                           type="submit">Регистрация</a>
                    </li>
                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">
                        <a href="{% url 'login' %}" class="nav-link btn btn-signin rounded-pill ps-4 pe-4 pt-2 pb-2"
                           type="submit">Войти</a>
                    </li>
                    <li class="nav-item mx-xl-3 mx-md-1 btn-sm">
                        <a href="{% url 'login' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"
                           type="submit">Войти</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>


{#<nav class="navbar navbar-expand-lg bg-body-tertiary">#}
{#        <div class="container-fluid ms-3 ms-3">#}
{#        <a class="navbar-brand" href="{% url 'clubs_app:home_page' %}">#}
{#            <img src="{% static 'images/logos/logo.svg' %}" alt="Logo" class="d-inline-block align-text-top"#}
{#                 width="80%">#}
{#        </a>#}
{#        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"#}
{#                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#            <ul class="navbar-nav me-auto">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="#">Главная</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Категории</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"#}
{#                       aria-expanded="false">#}
{#                        Мои клубы#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
{#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#            </ul>#}
{#            <ul class="navbar-nav ms-auto">#}
{#                {% if user.is_authenticated %}#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-signin rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">{{ user.username |split_string|first|truncatechars:20 }}</a>#}
{#                    </li>#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-sm">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">{{ user.username |split_string|first|truncatechars:10 }}</a>#}
{#                    </li>#}
{#                {% else %}#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                        <a href="{% url 'signup' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">Регистрация</a>#}
{#                    </li>#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-signin rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">Войти</a>#}
{#                    </li>#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-sm">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">Войти</a>#}
{#                    </li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}


{#<nav class="navbar navbar-expand-lg bg-body-tertiary">#}
{#    <div class="container-fluid">#}
{#        <a class="navbar-brand" href="#">#}
{#            <img src="{% static 'images/logos/logo.svg' %}" alt="Logo" class="d-inline-block align-text-top"#}
{#                 width="80%">#}
{#        </a>#}
{#        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"#}
{#                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#            <ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="#">Главная</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Категории</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Новости</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"#}
{#                       aria-expanded="false">#}
{#                        Мои клубы#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
{#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                </li>#}
{##}
{#            </ul>#}
{#            <ul class="navbar-nav ms-auto">#}
{#                {% if user.is_authenticated %}#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-signin rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">{{ user.username |split_string|first|truncatechars:20 }}</a>#}
{#                    </li>#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-sm">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">{{ user.username |split_string|first|truncatechars:10 }}</a>#}
{#                    </li>#}
{#                {% else %}#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                        <a href="{% url 'signup' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">Регистрация</a>#}
{#                    </li>#}
{#                <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                    <a href="{% url 'login' %}" class="nav-link "#}
{#                       type="submit"><i class="bi bi-person" style="font-size: 40px"></i></a>#}
{#                </li>#}
{#                <li class="nav-item mx-xl-3 mx-md-1 btn-lg">#}
{#                    <a href="{% url 'login' %}" class="nav-link "#}
{#                       type="submit"><i class="bi bi-calendar-plus" style="font-size: 40px"></i></a>#}
{#                </li>#}
{#                    <li class="nav-item mx-xl-3 mx-md-1 btn-sm">#}
{#                        <a href="{% url 'login' %}" class="nav-link btn btn-regist rounded-pill ps-4 pe-4 pt-2 pb-2"#}
{#                           type="submit">Войти</a>#}
{#                    </li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}