School_clubs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clubs_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('duty_app/', include('duty_app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
]

clubs_app/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'clubs_app'

urlpatterns = [
    path('', index, name='home_page'),
    path('create_club/', create_club, name='create_club'),
    path('list_club/<slug:cat_slug>', list_club, name='list_club'),
    path('join_club/<int:club_id>', join_club, name='join_club'),
    path('my_clubs/', my_clubs, name='my_clubs'),
    path('show_content/<slug:slug_club>/articles/', show_articles, name='show_articles'),
    path('show_content/acticles/<slug:slug_article>/', detail_articles, name='detail_articles'),
    path('show_content/<slug:slug_club>/messages/', show_messages, name='show_messages'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard_app/urls.py
from django.urls import path, include
from .views import index, members, delete_member, add_article, message, delete_content
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard_app'
urlpatterns = [
    path('<slug:slug_club>/profile/', index, name='profile'),
    path('<slug:slug_club>/members/', members, name='members'),
    path('<slug:slug_club>/<int:id_member>/delete/', delete_member, name='delete_member'),
    path('<slug:slug_club>/content/add_article', add_article, name='add_article'),
    path('<slug:slug_club>/add_message/', message, name='message'),
    path('content/delete/<str:model_name>/<slug:content_slug>/', delete_content, name='delete_content'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clubs_app/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from ckeditor.fields import RichTextField
import django


class MessageClub(models.Model):
    author_user = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, verbose_name='Отправитель')
    club_contains = models.ForeignKey('ClubModel', on_delete=models.CASCADE, verbose_name='Клуб', null=True)
    slug_content = models.SlugField(unique=True, max_length=512)

    title_msg = models.CharField(null=True, blank=False, max_length=128, verbose_name='Заголовок сообщения')
    body_msg = models.TextField(null=True, blank=False, verbose_name='Сообщение')
    date_load = models.DateField(default=django.utils.timezone.now, verbose_name='Дата')

    class Meta:
        verbose_name = 'Сообщения клубов'
        verbose_name_plural = 'Сообщения клубов'

    def get_delete_url(self):
        return reverse('dashboard_app:delete_content',
                       kwargs={'model_name': 'messageclub', 'content_slug': self.slug_content})


class ArticleClubModel(models.Model):
    author_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    club_contains = models.ForeignKey('ClubModel', on_delete=models.CASCADE, null=True)
    slug_content = models.SlugField(max_length=255, unique=True)

    title_article = models.CharField(max_length=128, verbose_name='Заголовок статьи', unique=True, blank=False)
    text_body = RichTextField(blank=False, null=True, verbose_name='Контент статьи')
    image = models.ImageField(upload_to='articles/', null=True, blank=False, verbose_name='Главное изображение статьи')

    def __str__(self):
        return self.title_article

    class Meta:
        verbose_name = 'Статьи клубов'
        verbose_name_plural = 'Статьи клубов'

    def get_absolute_url(self):
        return reverse('clubs_app:detail_articles', kwargs={'slug_article': self.slug_content})

    def get_delete_url(self):
        return reverse('dashboard_app:delete_content',
                       kwargs={'model_name': 'articleclubmodel', 'content_slug': self.slug_content})


class ClubModel(models.Model):
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, null=True, related_name='user_system')
    title_club = models.CharField(max_length=128, null=False, blank=False)
    cat_club = models.ForeignKey('CatClubModel', on_delete=models.CASCADE)
    info_club = models.TextField()
    days_event = models.CharField(max_length=100, null=True, blank=True)
    time_event = models.CharField(max_length=100, null=True, blank=True)
    price_club = models.CharField(max_length=256, null=True, blank=True)
    member = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='member_field')
    slug_club = models.SlugField(max_length=255, unique=True, null=True)

    def __str__(self):
        return self.title_club

    class Meta:
        verbose_name = 'Клубы'
        verbose_name_plural = 'Клубы'
        ordering = ['-id']


class CatClubModel(models.Model):
    cat = models.CharField(max_length=128, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='photos/', null=True)

    def __str__(self):
        return self.cat

    def get_absolute_url(self):
        return reverse('clubs_app:list_club', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категории клубов'
        verbose_name_plural = 'Категории клубов'

clubs_app/forms.py
from django import forms
from .models import ClubModel


class FormClubModel(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title_club'].label = 'Название клуба'
        self.fields['cat_club'].empty_label = 'Категория клуба не выбрана:'
        self.fields['cat_club'].label = 'Категория клуба'
        self.fields['info_club'].label = 'Информация о клубе'
        self.fields['days_event'].label = 'Дни проведения'
        self.fields['time_event'].label = 'Время проведения'
        self.fields['price_club'].label = 'Цена'

    class Meta:
        model = ClubModel
        fields = ["title_club", "cat_club", "info_club", "days_event", "time_event",
                  "price_club"]


        widgets = {
            'title_club': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'cat_club': forms.Select(attrs={'class': 'form-control form-control-lg'}),
            'info_club': forms.Textarea(attrs={'class': 'form-control form-control-lg', 'rows': 4}),
            'days_event': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'time_event': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'price_club': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
        }

clubs_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from pytils.translit import slugify
from django.db.models import Q
from django.apps import apps


def index(request):
    clubs_cat = CatClubModel.objects.all()
    context = {
        'clubs_cat': clubs_cat,
    }
    return render(request, template_name='clubs_app/index.html', context=context)


@login_required
def create_club(request):
    if request.method == 'POST':
        form = FormClubModel(request.POST)
        if form.is_valid():
            form.instance.manager = request.user
            form.instance.slug_club = slugify(form.instance.title_club)
            form.save()
            messages.success(request, 'Клуб создан')
            return redirect('clubs_app:home_page')
    else:
        form = FormClubModel()

    context = {
        'form': form,
    }
    return render(request, template_name='clubs_app/create_club.html', context=context)


@login_required
def list_club(request, cat_slug):
    if cat_slug == 'all_clubs':
        club_model = ClubModel.objects.all()
        cat = None
    else:
        cm = CatClubModel.objects.get(slug=cat_slug)
        club_model = ClubModel.objects.filter(cat_club=cm)
        cat = cm.cat

    context = {
        'club_model': club_model,
        'if_all_clubs': ('all_clubs' if cat_slug == 'all_clubs' else False),
        'if_category': ('category' if cat_slug not in ('my_clubs', 'all_clubs') else False),
        'cat': cat,
    }
    return render(request, template_name='clubs_app/list_club.html', context=context)


def join_club(request, club_id):
    club = ClubModel.objects.get(pk=club_id)
    club.member.add(request.user.id)

    messages.success(request, f'Вы вступили в клуб {club.title_club}')
    return redirect('clubs_app:home_page')


@login_required
def my_clubs(request):
    club_model = set(ClubModel.objects.filter(Q(manager=request.user) | Q(member=request.user)))
    context = {
        'club_model': club_model,
        'my_clubs': True,
    }

    return render(request, template_name='clubs_app/list_club.html', context=context)


def show_articles(request, slug_club):
    articles = ArticleClubModel.objects.filter(club_contains=ClubModel.objects.get(slug_club=slug_club))

    context = {
        'slug_club': slug_club,
        'articles': articles,
    }
    return render(request, template_name='clubs_app/show_articles.html', context=context)


def detail_articles(request, slug_article):
    article = ArticleClubModel.objects.get(slug_content=slug_article)

    context = {
        'title_article': article.title_article,
        'text_body': article.text_body,
        'author_user': article.author_user.username,
        'image': article.image,
        'slug_club': article.club_contains.slug_club,
    }
    return render(request, template_name='clubs_app/detail_articles.html', context=context)


def show_messages(request, slug_club):
    context = {
        'slug_club': slug_club,
        'messages': MessageClub.objects.filter(club_contains=ClubModel.objects.get(slug_club=slug_club))
    }

    return render(request, template_name='clubs_app/show_messages.html', context=context)

clubs_app/templates/clubs_app/create_club.html
{% extends 'clubs_app/base/base.html' %}

{% block title %}Создать клуб{% endblock title %}

{% block content %}

    <div class="container-fluid intro-block" style="background: #223A76; padding-top: 70px; padding-bottom: 70px;">
        <h2 style="font-size: 90px; font-weight: 600; color:white" class="text-center">Создать клуб</h2><br>
    </div>
    <br><br>


    <div class="container">
        <form method="post" action="{% url 'clubs_app:create_club' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <br><br><br>
{% endblock content %}

clubs_app/templates/clubs_app/dashboard.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
            crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>
  </head>
<body>
{% comment %}
<header class="d-flex flex-nowrap">

  <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 320px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <span class="fs-1">
          {{ user.username |truncatechars:14 }}
      </span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link link-body-emphasis items-sidebar" aria-current="page">
          <i class="bi bi-people"></i>
          Профиль
        </a>
      </li><br>
      <li>
        <a href="#" class="nav-link link-body-emphasis items-sidebar">
          <i class="bi bi-person-badge"></i>
          Участники
        </a>
      </li><br>
      <li>
        <a href="#" class="nav-link link-body-emphasis items-sidebar">
         <i class="bi bi-file-earmark-excel"></i>
          Содержание
        </a>
      </li><br>
      <li>
        <a href="#" class="nav-link link-body-emphasis items-sidebar">
          <i class="bi bi-chat-dots"></i>
          Уведомления
        </a>
      </li><br>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>

  <div class="b-example-divider b-example-vr"></div>
</header>
{% endcomment %}


<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-body-tertiary sidebar collapse"><br>
      <h1>{{ user.username }}</h1>
      <hr>
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item ">
            <a class="nav-link items-sidebar" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
              Профиль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link items-sidebar" href="#">
              <span data-feather="file" class="align-text-bottom"></span>
              Участники
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link items-sidebar" href="#">
              <span data-feather="users" class="align-text-bottom"></span>
              Содержание
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link items-sidebar" href="#">
              <span data-feather="layers" class="align-text-bottom"></span>
              Уведомления
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <br>
      <h1 class="text-center">Профиль клуба</h1>




    </main>
  </div>
</div>

</body>
</html>

clubs_app/templates/clubs_app/detail_articles.html
{% extends 'clubs_app/base/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
{% endblock %}
{% block title %}Смотреть контент{% endblock title %}

{% block content %}<br><br>
        {% include 'clubs_app/base/nav.html' %}


    <div class="container">
        <div class="card mb-3" style="border: 1px solid #b8b8b8">
            <img src="{{ image.url }}" class="card-img-top" width="100%">
            <div class="card-body"><br>
                <h2 class="card-title">{{ title_article }}</h2>
                <p class="card-text">{{ text_body|safe }}</p><br>
                <p class="card-text">Автор: {{ author_user }}</p>

                <p class="card-text"><a class="btn btn-outline-secondary"
                                        href="{% url 'clubs_app:show_articles' slug_club %}">Назад</a></p>
            </div>
        </div>
    </div>



{% endblock content %}

clubs_app/templates/clubs_app/index.html
{% extends 'clubs_app/base/base.html' %}
{% load static %}

{% block title %}Главная страница{% endblock title %}
{% load static %}
{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="container">
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid intro-block" style="background: #223A76; padding-top: 70px; padding-bottom: 70px;">
        <h2 style="font-size: 90px; font-weight: 600; color:white" class="text-center main-title">Школьные клубы</h2><br>
        <div class="text-center" style="width: 100%;">
            <a class="btn btn-join-club-intro" href="{% url 'clubs_app:list_club' cat_slug='all_clubs' %}">Вступить в клуб</a>
        </div>
    </div>


    <br><br><br>
    <div class="container"
         style="background-color: #c8dbef; border-radius: 30px; padding-top: 30px; padding-bottom: 40px; padding-left: 40px; padding-right: 40px;">
        <h2 style="font-size: 50px; color: black">Создавай. Присоединяйся. Узнавай.</h2><br>
        <br>
        <div class=" row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card h-100">
                    <img src="{% static 'clubs_app/images/home_page/1.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="text-center">
                            <a href="{% url 'clubs_app:list_club' cat_slug='all_clubs' %}" style="text-decoration: none;"
                               class="text-center intro-block-links">Наши клубы <i
                                    class="bi bi-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="{% static 'clubs_app/images/home_page/2.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="text-center">
                            <a href="{% url 'clubs_app:create_club' %}"
                               style="text-decoration: none;" class="text-center intro-block-links">Создать клуб <i
                                    class="bi bi-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="{% static 'clubs_app/images/home_page/3.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="text-center">
                            <a href="#" style="text-decoration: none;" class="text-center intro-block-links">Новости <i
                                    class="bi bi-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <div class="text-center">
            <p style="width: 100%; font-size: 30px; color:#2B74B7">Клуб - место встречи людей с едиными интересами,
                зачастую
                официально объединённых в сообщество, организацию или ассоциацию.</p>
        </div>
    </div>
    <br><br><br><br>


    <h2 style="font-size: 50px; font-weight: 600; color: black;" class="text-center">Выбери свое направление</h2><br>

    <div class="container" style="background-color: #c8dbef; border-radius: 30px; padding-top: 30px; padding-bottom: 40px; padding-left: 40px; padding-right: 40px;">
        <div class="row row-cols-1 row-cols-md-3 row-cols-sm-2 row-cols-lg-4  g-4">
            {% for club in clubs_cat %}
                <div class="col">
                    <div class="card h-100" style="background-color: #c8dbef;">

                        {% if club.image %}
                            <img src="{{ club.image.url }}"
                             class="card-img-top d-flex justify-content-center"
                             style="width: 90%;display:block; margin:auto;">
                        {% else %}
                        {% endif %}

                        <div class="card-body">
                            <div class="text-center d-flex align-items-center justify-content-center"
                                 style="background-color: #2B74B7; border-radius: 10px 100px / 120px; height: 70px;">
                                <a href="{{ club.get_absolute_url }}" style="text-decoration: none; color: white"
                                   class="text-center intro-block-links">{{ club.cat }}</a>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
    <br><br><br><br><br><br>



    <div class="bg-image"
         style="background-image: url('{% static 'images/home_page/blockBI.png' %}'); padding-bottom: 40px;">
        <div class="container">
            <div class="support-block-text"
                 style="background-color: #223A76; border-radius: 10px 100px / 120px; padding-left: 30px; padding-top: 15px; padding-bottom: 15px; padding-right: 30px;">
                <p style="font-size: 40px; color: white; font-weight: 600;">Поддержите разработчиков</p>
            </div>
            <br><br><br>

        </div>
        <div class="container">
            <div class="" style="background-color: #2B74B7; border-radius: 10px 100px / 120px; padding: 30px;">
                <p style="font-size: 30px; color: white; font-weight: 600;">Поддержите нас посоветуйте, что бы вы хотели
                    добавитть, функционал, бла бла бла. Добавьте сами текст пожалуйста...Что нибудь напишите бред какой
                    нить, серн читать никто не собираеьтся.)</p>
            </div>
            <br><br>

            <div class="d-flex justify-content-end">
                <div style="background-color: #223A76;border-radius: 10px 100px / 120px; padding-left: 30px; padding-top: 15px; padding-bottom: 15px; padding-right: 30px;"
                     class="justify-content-end">
                    <a href="#" style="text-decoration: none;"><p style="color: white; font-size: 40px;"
                                                                  class="text-center">Пройти опрос <i
                            class="bi bi-arrow-right"></i></p></a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

clubs_app/templates/clubs_app/list_club.html
{% extends 'clubs_app/base/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
{% endblock %}
{% block title %}Наши клубы{% endblock title %}

{% block content %}
    <br><br><br>
    <div class="container">
        {% if if_all_clubs == 'all_clubs' %}
            <h1>Все клубы</h1><br><br>
        {% elif if_category == 'category' %}
            <h1>Все клубы: {{ cat }}</h1><br><br>
        {% else %}
            <h1>Мои клубы</h1><br><br>
        {% endif %}
        <div class="row row-cols-1 row-cols-md-3 g-4">

            {% for club in club_model %}

                <div class="col ">
                    <div class="card h-100 list-club-table">
                        {#                    <img src="..." class="card-img-top" alt="...">#}
                        <div style="border: 1px solid #223a76; height:80px; background: #223a76"
                             class="d-flex align-items-center justify-content-center">
                            <h3 style="color:white !important;" class="">{{ club.title_club }}</h3>
                        </div>
                        <div class="card-body">
                            <div class="text-center d-flex align-items-center justify-content-center"
                                 style="background-color: white; border-radius: 10px 100px / 120px; height: 50px; width: 250px">
                                <a href="#" style="text-decoration: none; color: black"
                                   class="text-center intro-block-links">{{ club.cat_club }}</a>
                            </div>
                            <br>
                            {% if club.price_club %}
                                <h4><i class="bi bi-wallet2"></i> {{ club.price_club }}</h4><br>
                            {% endif %}


                            {% if club.days_event %}
                                <h4><i class="bi bi-calendar3"></i> {{ club.days_event }}</h4><br>
                            {% endif %}



                            {% if club.time_event %}
                                <h4><i class="bi bi-alarm"></i> {{ club.time_event }}</h4><br>
                            {% endif %}

                            <h3><i class="bi bi-person-circle"></i> {{ club.manager }}</h3>

                        </div>

                        {% if request.user == club.manager %}
                            <div class="card-footer" style="background: #c8dbef">
                                <a class="btn btn-warning  mx-auto" style="display: block"
                                   href="{% url 'dashboard_app:profile' slug_club=club.slug_club %}">В панель
                                    управления</a>
                            </div>
                        {% elif request.user in club.member.all %}
                            <div class="card-footer" style="background: #c8dbef">
                                <a class="btn btn-success  mx-auto" style="display: block"
                                   href="{% url 'clubs_app:show_articles' slug_club=club.slug_club %}">Смотреть</a>
                            </div>
                        {% else %}

                            <div class="card-footer" style="background: #c8dbef">
                                <a class="btn btn-primary  mx-auto" style="display: block"
                                   href="{% url 'clubs_app:join_club' club_id=club.pk %}">Вступить</a>
                            </div>
                        {% endif %}


                    </div>
                </div>

            {% endfor %}


        </div>
    </div>
    <br><br><br>

{% endblock content %}

clubs_app/templates/clubs_app/show_articles.html
{% extends 'clubs_app/base/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
{% endblock %}
{% block title %}Смотреть контент{% endblock title %}

{% block content %}<br><br>
    {% include 'clubs_app/base/nav.html' %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="container">
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% endif %}

    {% for article in articles %}
        <div class="container">
            <div class="card mb-3" style="border: 1px solid #b8b8b8">
                <img src="{{ article.image.url }}" class="card-img-top" width="100%">
                <div class="card-body"><br>
                    <h2 class="card-title">{{ article.title_article }}</h2>
                    <p class="card-text">{{ article.text_body|safe|linebreaks|truncatechars:400 }}</p><br>
                    <p class="card-text">
                        <a class="btn btn-outline-secondary" href="{{ article.get_absolute_url }}">Читать
                        далее {{ article.manager }}</a>


                    {% if request.user == article.author_user %}
                        <a class="btn btn-outline-danger" href="{{ article.get_delete_url }}">Удалить</a>
                    {% endif %}


                    </p>
                </div>
            </div>
        </div><br>
    {% endfor %}





{% endblock content %}