School_clubs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clubs_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('duty_app/', include('duty_app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
]

duty_app/urls.py
from django.urls import include, path
from .views import *

app_name = 'duty_app'

urlpatterns = [
    path('', home, name='home'),
    path('action_duty/<str:type_action>/<int:id_person>/', action_duty, name='action_duty'),
    # path('is_duty/', home, name='is_duty'),
]

duty_app/models.py
from django.db import models


class PersonModel(models.Model):
    name = models.CharField(max_length=128, verbose_name='Ученик', null=True)
    # True - был дежурным. False - не был
    active = models.BooleanField(default=False, verbose_name='Дежурил', null=True)
    date_duty = models.DateTimeField(verbose_name='Дата', null=True)

    class Meta:
        verbose_name = 'Участники'
        verbose_name_plural = 'Участники'

    def __str__(self):
        return self.name

duty_app/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import PersonModel
# import django
# import datetime
from django.utils import timezone


@login_required
def home(request):
    if request.user.username != 'ordenmeny':
        return redirect('clubs_app:home_page')

    person_model = PersonModel.objects.all()

    context = {
        'person_model': person_model,
    }

    return render(request, template_name='duty_app/index.html', context=context)


def action_duty(request, type_action, id_person):
    person_model = PersonModel.objects.get(pk=id_person)
    context = {

    }
    if type_action == 'to_duty':
        # установить, что человек подежурил
        person_model.active = True
        person_model.date_duty = timezone.now()
        print(timezone.now())
        person_model.save()
        return redirect('duty_app:home')
    elif type_action == 'from_duty':
        person_model.active = False
        person_model.date_duty = None
        person_model.save()
        # установить, что человек НЕ подежурил
        return redirect('duty_app:home')

duty_app/templates/duty_app/index.html
{% extends "duty_app/base/base.html" %}
{% block content %}
<ol class="list-group list-group-numbered">

    {% for person in person_model %}

    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">{{person.name}}</div>
            {% if person.active %}
            {{ person.date_duty }}

            {% else %}
            <p>Не дежурил</p>

            {% endif %}



        </div>
        <span class="badge rounded-pill">

            {% if person.active == True %}
            <a onclick="return confirm('Вы уверены, что хотите выполнить это действие?')" type="button" class="btn btn-success btn-sm" href="{% url 'duty_app:action_duty' type_action='from_duty' id_person=person.id %}">Дежурил</a>

            {% else %}
            <a onclick="return confirm('Вы уверены, что хотите выполнить это действие?')" type="button" class="btn btn-danger btn-sm" href="{% url 'duty_app:action_duty' type_action='to_duty' id_person=person.id %}">Не дежурил</a>

            {% endif %}


        </span>
    </li>
    {% endfor %}
</ol>

{% endblock %}